import pyromat as pm
import numpy as np

pm.config["unit_pressure"] = "kPa"

# 1-2 - low pressure pump, 2-3 (6-3) - economiser,
# 3-4 - high pressure pump, 4-5 boiler,
# 5-5 (5-7) - turbine, 7-1 condenser

mp_water = pm.get("mp.H2O")

# LOW PRESSURE PUMP

p1 = 10
p2 = 400

v1 = 1/mp_water.ds(p=p1)[0]
w_pump1 = v1 * (p2-p1)

h1 = mp_water.hs(p=p1)[0]
h2 = h1 + w_pump1

print(f"Work required by low pressure pump: {round(float(w_pump1),4)} kJ/kg")

# TURBINE

p5 = 4000
T5 = 400 + 273.15
p6 = 400

h5 = mp_water.h(p=p5, T=T5)
s5 = mp_water.s(p=p5, T=T5)

s6 = s5
T6, x6 = mp_water.T_s(s=s6, p=p6, quality=True)

h6 = mp_water.h(x=x6, p=p6)

print(f"Quality of bled steam: {round(float(x6),4)}")

# ECONOMIZER

p3 = 400
h3 = mp_water.hs(p=p3)[0]

y = (h2-h3)/(h2-h6)
print(f"y =  {round(float(y),4)}")

p7 = p1
s7 = s5
T7, x7 = mp_water.T_s(s=s7, p=p7, quality=True)
h7 = mp_water.h(x=x7, p=p7)
w_t = h5 - y*h6 - (1-y)*h7

print(f"Work generated by turbine = {round(float(w_t),4)} kJ/kg")

# HIGH PRESSURE PUMP

p4 = 4000
v3 = 1/mp_water.ds(p=p3)[0]
w_pump2 = v3*(p4-p3)

print(f"Work required by high pressure pump: {round(float(w_pump2),4)} kJ/kg")

# BOILER

h4 = h3 + w_pump2
q_H = h5-h4

print(f"Heat input by boiler = {round(float(q_H),4)} kJ/kg")

eff_th = (w_t - w_pump1*(1-y) - w_pump2)/q_H * 100

print(f"Thermal efficiency = {round(float(eff_th),4)} %")


