import pyromat as pm
import numpy as np

pm.config["unit_pressure"] = "kPa"

mp_water = pm.get("mp.H2O")

p1 = 10
p2 = 4000

# PUMP

v1 = 1/mp_water.ds(p=p1)[0]
w_p = v1 * (p2-p1)

print(f"Work required by pump: {round(float(w_p),4)} kJ/kg")

h1 = mp_water.hs(p=p1)[0]
h2 = h1 + w_p

#print(f"h2 = {round(float(h2),4)} kJ/kg")

p3 = p2
T3 = 400+273.15
h3 = mp_water.h(p=p3, T=T3)
s3 = mp_water.s(p=p3, T=T3)

p4 = 400
s4 = s3
x4 = mp_water.T_s(s=s4, p=p4, quality=True)[1]
h4 = mp_water.h(x=x4, p=p4)

w_HPt = h3-h4

print(f"Quality of mid-steam = {round(float(x4),4)}")
print(f"Work generated by high pressure turbine = {round(float(w_HPt),4)} kJ/kg")

p5 = p4
T5 = 400+273.15
h5 = mp_water.h(p=p5, T=T5)
s5 = mp_water.s(p=p5, T=T5)

p6 = p1 
s6 = s5

x6 = mp_water.T_s(s=s6, p=p6, quality=True)[1]
h6 = mp_water.h(x=x6, p=p6)

w_LPt = h5 - h6

print(f"Quality of low-steam = {round(float(x6),4)}")
print(f"Work generated by low pressure turbine = {round(float(w_LPt),4)} kJ/kg")
print(f"Work generated by both turbines = {round(float(w_LPt+w_HPt),4)} kJ/kg")

q_H = (h3-h2)+(h5-h4)

print(f"Heat input by boiler = {round(float(q_H),4)} kJ/kg")

q_L = h6-h1

print(f"Heat rejected by condenser = {round(float(q_L),4)} kJ/kg")

eff_th = (w_LPt + w_HPt - w_p) / q_H * 100 

print(f"Thermal efficiency = {round(float(eff_th),4)} %")
